//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Tales.teste {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://teste.com/", ConfigurationName="teste.WsTeste")]
    public interface WsTeste {
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://teste.com/)
        [System.ServiceModel.OperationContractAttribute(Action="http://teste.com/WsTeste/SomaRequest", ReplyAction="http://teste.com/WsTeste/SomaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Projeto_Tales.teste.SomaResponse Soma(Projeto_Tales.teste.SomaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://teste.com/WsTeste/SomaRequest", ReplyAction="http://teste.com/WsTeste/SomaResponse")]
        System.Threading.Tasks.Task<Projeto_Tales.teste.SomaResponse> SomaAsync(Projeto_Tales.teste.SomaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Soma", WrapperNamespace="http://teste.com/", IsWrapped=true)]
    public partial class SomaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public SomaRequest() {
        }
        
        public SomaRequest(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SomaResponse", WrapperNamespace="http://teste.com/", IsWrapped=true)]
    public partial class SomaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public SomaResponse() {
        }
        
        public SomaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsTesteChannel : Projeto_Tales.teste.WsTeste, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsTesteClient : System.ServiceModel.ClientBase<Projeto_Tales.teste.WsTeste>, Projeto_Tales.teste.WsTeste {
        
        public WsTesteClient() {
        }
        
        public WsTesteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsTesteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsTesteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsTesteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Projeto_Tales.teste.SomaResponse Projeto_Tales.teste.WsTeste.Soma(Projeto_Tales.teste.SomaRequest request) {
            return base.Channel.Soma(request);
        }
        
        public int Soma(int arg0, int arg1) {
            Projeto_Tales.teste.SomaRequest inValue = new Projeto_Tales.teste.SomaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Projeto_Tales.teste.SomaResponse retVal = ((Projeto_Tales.teste.WsTeste)(this)).Soma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Projeto_Tales.teste.SomaResponse> Projeto_Tales.teste.WsTeste.SomaAsync(Projeto_Tales.teste.SomaRequest request) {
            return base.Channel.SomaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Projeto_Tales.teste.SomaResponse> SomaAsync(int arg0, int arg1) {
            Projeto_Tales.teste.SomaRequest inValue = new Projeto_Tales.teste.SomaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((Projeto_Tales.teste.WsTeste)(this)).SomaAsync(inValue);
        }
    }
}
