//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Tales.cpfvalida {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://validar/", ConfigurationName="cpfvalida.validacpf")]
    public interface validacpf {
        
        // CODEGEN: Gerando contrato de mensagem porque o namespace de parte da mensagem () não corresponde ao valor padrão (http://validar/)
        [System.ServiceModel.OperationContractAttribute(Action="http://validar/validacpf/validarCPFRequest", ReplyAction="http://validar/validacpf/validarCPFResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Projeto_Tales.cpfvalida.validarCPFResponse validarCPF(Projeto_Tales.cpfvalida.validarCPFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://validar/validacpf/validarCPFRequest", ReplyAction="http://validar/validacpf/validarCPFResponse")]
        System.Threading.Tasks.Task<Projeto_Tales.cpfvalida.validarCPFResponse> validarCPFAsync(Projeto_Tales.cpfvalida.validarCPFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarCPF", WrapperNamespace="http://validar/", IsWrapped=true)]
    public partial class validarCPFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long arg0;
        
        public validarCPFRequest() {
        }
        
        public validarCPFRequest(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarCPFResponse", WrapperNamespace="http://validar/", IsWrapped=true)]
    public partial class validarCPFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public validarCPFResponse() {
        }
        
        public validarCPFResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface validacpfChannel : Projeto_Tales.cpfvalida.validacpf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class validacpfClient : System.ServiceModel.ClientBase<Projeto_Tales.cpfvalida.validacpf>, Projeto_Tales.cpfvalida.validacpf {
        
        public validacpfClient() {
        }
        
        public validacpfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public validacpfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public validacpfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public validacpfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Projeto_Tales.cpfvalida.validarCPFResponse Projeto_Tales.cpfvalida.validacpf.validarCPF(Projeto_Tales.cpfvalida.validarCPFRequest request) {
            return base.Channel.validarCPF(request);
        }
        
        public bool validarCPF(long arg0) {
            Projeto_Tales.cpfvalida.validarCPFRequest inValue = new Projeto_Tales.cpfvalida.validarCPFRequest();
            inValue.arg0 = arg0;
            Projeto_Tales.cpfvalida.validarCPFResponse retVal = ((Projeto_Tales.cpfvalida.validacpf)(this)).validarCPF(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Projeto_Tales.cpfvalida.validarCPFResponse> Projeto_Tales.cpfvalida.validacpf.validarCPFAsync(Projeto_Tales.cpfvalida.validarCPFRequest request) {
            return base.Channel.validarCPFAsync(request);
        }
        
        public System.Threading.Tasks.Task<Projeto_Tales.cpfvalida.validarCPFResponse> validarCPFAsync(long arg0) {
            Projeto_Tales.cpfvalida.validarCPFRequest inValue = new Projeto_Tales.cpfvalida.validarCPFRequest();
            inValue.arg0 = arg0;
            return ((Projeto_Tales.cpfvalida.validacpf)(this)).validarCPFAsync(inValue);
        }
    }
}
